
package service.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HackServiceImplService", targetNamespace = "http://webService/", wsdlLocation = "http://172.31.13.53:8080/HackProject/hackService?wsdl")
public class HackServiceImplService
    extends Service
{

    private final static URL HACKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HACKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HACKSERVICEIMPLSERVICE_QNAME = new QName("http://webService/", "HackServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.31.13.53:8080/HackProject/hackService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HACKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HACKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HackServiceImplService() {
        super(__getWsdlLocation(), HACKSERVICEIMPLSERVICE_QNAME);
    }

    public HackServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HACKSERVICEIMPLSERVICE_QNAME, features);
    }

    public HackServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HACKSERVICEIMPLSERVICE_QNAME);
    }

    public HackServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HACKSERVICEIMPLSERVICE_QNAME, features);
    }

    public HackServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HackServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HackService
     */
    @WebEndpoint(name = "HackServiceImplPort")
    public HackService getHackServiceImplPort() {
        return super.getPort(new QName("http://webService/", "HackServiceImplPort"), HackService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HackService
     */
    @WebEndpoint(name = "HackServiceImplPort")
    public HackService getHackServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "HackServiceImplPort"), HackService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HACKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HACKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HACKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
